[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "rex-auth-server"
version = "1.0.0"
description = "Tenant-aware authentication microservice for SMART HOME ASSISTANT ROBOT"

[tool.isort]
profile = "black"
line_length = 88
